<template><div><h1 id="logic" tabindex="-1"><a class="header-anchor" href="#logic"><span>Logic</span></a></h1>
<p>To check for specific conditions in your data, Openmadness makes it easy to compare numbers within your arrays. These operations create a new Openmadness array where each value is true or false (also known as a boolean).</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> sensorReadings <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sensor Readings:"</span><span class="token punctuation">,</span> sensorReadings<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is each reading greater than 20?</span></span>
<span class="line"><span class="token keyword">const</span> aboveThreshold <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">greaterThan</span><span class="token punctuation">(</span><span class="token number">20</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings > 20:"</span><span class="token punctuation">,</span> aboveThreshold<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [false, true, false, true, false, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is each reading less than or equal to 15?</span></span>
<span class="line"><span class="token keyword">const</span> belowOrEqual <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">lessThanOrEqual</span><span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings &lt;= 15:"</span><span class="token punctuation">,</span> belowOrEqual<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [true, false, true, false, false, false]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is any reading exactly 30?</span></span>
<span class="line"><span class="token keyword">const</span> isThirty <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">equal</span><span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings == 30:"</span><span class="token punctuation">,</span> isThirty<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [false, false, false, false, false, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is any reading NOT equal to 19?</span></span>
<span class="line"><span class="token keyword">const</span> notNineteen <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">notEqual</span><span class="token punctuation">(</span><span class="token number">19</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings != 19:"</span><span class="token punctuation">,</span> notNineteen<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [true, true, true, true, false, true]</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


