<template><div><h1 id="creating-arrays" tabindex="-1"><a class="header-anchor" href="#creating-arrays"><span>Creating Arrays</span></a></h1>
<p>To create an array in the <code v-pre>openMadness</code> library, import the <code v-pre>omArray</code> function at the top of your code and enclose the list of items you want to store in the <code v-pre>omArray[ ]</code> method.</p>
<p><strong>Example</strong>:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> myArray<span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="example-use-case" tabindex="-1"><a class="header-anchor" href="#example-use-case"><span>Example Use Case</span></a></h2>
<p>Let’s assume you want to store a list of product prices in different currencies. You can create an array variable and pass in the list of prices you want to store temporarily.
I.e.,</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> productPrices <span class="token operator">=</span> <span class="token function">omArray</span> <span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// this stores all your product prices</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>Now that you have stored these prices in a single variable, you can easily retrieve each price.</p>
<p>Check out the “Accessing Array Elements” page for more information about how to retrieve elements in an array.</p>
</div></template>


