<template><div><h1 id="tutorials" tabindex="-1"><a class="header-anchor" href="#tutorials"><span>Tutorials</span></a></h1>
<p>Openmadness Tutorials
Welcome to the Openmadness Tutorials. This section is your starting point for exploring the core concepts of Openmadness, a beginner-friendly JavaScript library designed to make array and mathematical operations fast and intuitive.These topics form the foundation of working with Openmadness. Master them, and you'll be well-equipped to build confidently and efficiently.</p>
<h2 id="fundamentals" tabindex="-1"><a class="header-anchor" href="#fundamentals"><span>Fundamentals</span></a></h2>
<p>These topics form the foundation of working with Openmadness. Master them, and you'll be well-equipped to build confidently and efficiently.</p>
<h3 id="basic-arithmetic" tabindex="-1"><a class="header-anchor" href="#basic-arithmetic"><span>Basic Arithmetic</span></a></h3>
<p>Openmadness makes performing common math operations on lists of numbers (which we call arrays) super easy. Instead of performing calculations one by one, Openmadness lets you apply operations to entire arrays at once.
When you use an arithmetic method like add() or multiply() on an Openmadness array, it applies that operation to every corresponding number in the array. If you add a single number (a scalar), it's added to every element in the array.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Create Openmadness arrays</span></span>
<span class="line"><span class="token keyword">const</span> dailySales <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">150</span><span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> marketingSpend <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Daily Sales:"</span><span class="token punctuation">,</span> dailySales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Marketing Spend:"</span><span class="token punctuation">,</span> marketingSpend<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Addition (+) ---</span></span>
<span class="line"><span class="token comment">// Add two arrays (element-wise)</span></span>
<span class="line"><span class="token keyword">const</span> totalRevenue <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Total Revenue (Sales + Spend):"</span><span class="token punctuation">,</span> totalRevenue<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [110, 175, 240]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Add a scalar to an array</span></span>
<span class="line"><span class="token keyword">const</span> salesIncrease <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">50</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sales after $50 increase:"</span><span class="token punctuation">,</span> salesIncrease<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [150, 200, 250]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Subtraction (-) ---</span></span>
<span class="line"><span class="token keyword">const</span> netSales <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">subtract</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Net Sales (Sales - Spend):"</span><span class="token punctuation">,</span> netSales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [90, 125, 160]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Multiplication (*) ---</span></span>
<span class="line"><span class="token keyword">const</span> doubledSales <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">multiply</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Doubled Sales:"</span><span class="token punctuation">,</span> doubledSales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [200, 300, 400]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Division (/) ---</span></span>
<span class="line"><span class="token keyword">const</span> salesRatio <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">divide</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sales Ratio (Sales / Spend):"</span><span class="token punctuation">,</span> salesRatio<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [10, 6, 5]</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="data-types" tabindex="-1"><a class="header-anchor" href="#data-types"><span>Data Types</span></a></h3>
<p>In Openmadness, we primarily work with numbers. These can be whole numbers (such as 10, 500) or numbers with decimal points (such as 3.14, 0.5).
While JavaScript has other data types (like strings for text or booleans for true/false values), Openmadness functions are designed for numerical calculations. If you try to include non-numbers, Openmadness might convert them to NaN (Not a Number) if it can't understand them.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// An array of numbers - perfect for Openmadness!</span></span>
<span class="line"><span class="token keyword">const</span> prices <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">24.99</span><span class="token punctuation">,</span> <span class="token number">12.50</span><span class="token punctuation">,</span> <span class="token number">5.00</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Numeric prices:"</span><span class="token punctuation">,</span> prices<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// What happens if we try to include a string?</span></span>
<span class="line"><span class="token keyword">const</span> mixedItems <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token string">'apple'</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Mixed data:"</span><span class="token punctuation">,</span> mixedItems<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [10, NaN, 20]</span></span>
<span class="line"><span class="token comment">// 'apple' can't be converted to a number, so it becomes NaN.</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container note">
<p class="hint-container-title">Note</p>
<p>For reliable results, always provide numbers to Openmadness arrays.</p>
</div>
<h3 id="shape" tabindex="-1"><a class="header-anchor" href="#shape"><span>Shape</span></a></h3>
<p>The shape of an Openmadness array describes its dimensions or structure. Think of it as how your data is organized – like the rows and columns of a spreadsheet.</p>
<ul>
<li>A simple list of numbers has one dimension.</li>
<li>A table of numbers has two dimensions (rows and columns).
The shape property returns an array indicating the size of each dimension.</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// A 1-dimensional array (like a single list)</span></span>
<span class="line"><span class="token keyword">const</span> dailyVisitors <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">1000</span><span class="token punctuation">,</span> <span class="token number">1200</span><span class="token punctuation">,</span> <span class="token number">950</span><span class="token punctuation">,</span> <span class="token number">1300</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Daily Visitors data:"</span><span class="token punctuation">,</span> dailyVisitors<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of Daily Visitors:"</span><span class="token punctuation">,</span> dailyVisitors<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [4]</span></span>
<span class="line"><span class="token comment">// It has 4 elements in its single dimension.</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// A 2-dimensional array (like a grid or table)</span></span>
<span class="line"><span class="token keyword">const</span> quarterlySales <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">]</span><span class="token punctuation">,</span>  <span class="token comment">// Q1 sales for 3 regions</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">110</span><span class="token punctuation">,</span> <span class="token number">130</span><span class="token punctuation">,</span> <span class="token number">95</span><span class="token punctuation">]</span><span class="token punctuation">,</span>  <span class="token comment">// Q2 sales for 3 regions</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">105</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">]</span>  <span class="token comment">// Q3 sales for 3 regions</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nQuarterly Sales data:\n"</span><span class="token punctuation">,</span> quarterlySales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of Quarterly Sales:"</span><span class="token punctuation">,</span> quarterlySales<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [3, 3]</span></span>
<span class="line"><span class="token comment">// This means 3 rows and 3 columns.</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Understanding shape is crucial because many operations require arrays to have compatible shapes.</p>
<h3 id="size" tabindex="-1"><a class="header-anchor" href="#size"><span>Size</span></a></h3>
<p>The size of an Openmadness array is simply the total number of elements it contains. It's the grand count of all the individual numbers, regardless of how they're organized into dimensions.
You can find the size using the size property.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> temperatures <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span> <span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Temperatures:"</span><span class="token punctuation">,</span> temperatures<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of temperatures:"</span><span class="token punctuation">,</span> temperatures<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [5]</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Size of temperatures:"</span><span class="token punctuation">,</span> temperatures<span class="token punctuation">.</span>size<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 5</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> productMatrix <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">60</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nProduct Matrix:\n"</span><span class="token punctuation">,</span> productMatrix<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of Product Matrix:"</span><span class="token punctuation">,</span> productMatrix<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [3, 2] (3 rows, 2 columns)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Size of Product Matrix:"</span><span class="token punctuation">,</span> productMatrix<span class="token punctuation">.</span>size<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 6 (3 * 2 = 6 total elements)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="axes" tabindex="-1"><a class="header-anchor" href="#axes"><span>Axes</span></a></h3>
<p>Axes refer to the different dimensions along which you can perform operations in your data. In a 2D array (like a grid), you have two main axes:
Axis 0: Runs vertically, down the rows.
Axis 1: Runs horizontally, across the columns.
Why does this matter? Many Openmadness functions (like average() or sum()) allow you to specify an axis to operate on that particular dimension, rather than on the entire dataset.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> examScores <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">80</span><span class="token punctuation">,</span> <span class="token number">85</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token comment">// Student 1 scores (Math, Science, History)</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">,</span> <span class="token number">88</span><span class="token punctuation">]</span>  <span class="token comment">// Student 2 scores</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span> <span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Exam Scores:\n"</span><span class="token punctuation">,</span> examScores<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Sum of all scores (no axis specified)</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Total sum of all scores:"</span><span class="token punctuation">,</span> examScores<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 513</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Sum along axis 0 (down the columns) - sum for each subject</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> subjectTotals <span class="token operator">=</span> examScores<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sum per Subject (Axis 0):"</span><span class="token punctuation">,</span> subjectTotals<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [155, 175, 178]</span></span>
<span class="line"><span class="token comment">// (80+75), (85+90), (90+88)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Sum along axis 1 (across the rows) - sum for each student</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> studentTotals <span class="token operator">=</span> examScores<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sum per Student (Axis 1):"</span><span class="token punctuation">,</span> studentTotals<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [255, 253]</span></span>
<span class="line"><span class="token comment">// (80+85+90), (75+90+88)</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Don't worry if the axis seems tricky at first. It becomes clearer as you use it in practice for operations like calculating averages or sums.</p>
<h3 id="arrays" tabindex="-1"><a class="header-anchor" href="#arrays"><span>Arrays</span></a></h3>
<p>The Openmadness Array is the fundamental building block of this library. While regular JavaScript arrays ([1, 2, 3]) are just lists of values, Openmadness wraps these into its special object (om.array()). This wrapper provides all the powerful methods for math, statistics, and data manipulation.
To start working with Openmadness, you'll always convert your standard JavaScript arrays (or even single numbers) into an om.array.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// A regular JavaScript array</span></span>
<span class="line"><span class="token keyword">const</span> rawData <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Plain JavaScript array:"</span><span class="token punctuation">,</span> rawData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Convert it into an Openmadness array</span></span>
<span class="line"><span class="token keyword">const</span> omData <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span>rawData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Openmadness array object:"</span><span class="token punctuation">,</span> omData<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Shows the Openmadness object structure</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Data inside omData:"</span><span class="token punctuation">,</span> omData<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Access the underlying numbers</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// You can also create an Openmadness array directly</span></span>
<span class="line"><span class="token keyword">const</span> omDirect <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Directly created Openmadness array:"</span><span class="token punctuation">,</span> omDirect<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// The power of Openmadness:</span></span>
<span class="line"><span class="token comment">// With plain JS, adding 5 to each element requires a loop:</span></span>
<span class="line"><span class="token keyword">const</span> rawDataPlus5 <span class="token operator">=</span> rawData<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token parameter">num</span> <span class="token operator">=></span> num <span class="token operator">+</span> <span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Plain JS add 5:"</span><span class="token punctuation">,</span> rawDataPlus5<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [15, 25, 35, 45]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// With Openmadness, it's a single, clear method call:</span></span>
<span class="line"><span class="token keyword">const</span> omDataPlus5 <span class="token operator">=</span> omData<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Openmadness add 5:"</span><span class="token punctuation">,</span> omDataPlus5<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [15, 25, 35, 45]</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="statistics" tabindex="-1"><a class="header-anchor" href="#statistics"><span>Statistics</span></a></h3>
<h4 id="minimum-and-maximum-values" tabindex="-1"><a class="header-anchor" href="#minimum-and-maximum-values"><span>Minimum and Maximum Values</span></a></h4>
<p>Openmadness provides simple methods to quickly find the extreme values in your dataset: the smallest number using min() and the largest using max(). This helps you quickly see how high and low your numbers go.</p>
<ul>
<li>min()
Get the lowest value in your Openmadness array.</li>
<li>max()
Get the highest value in your Openmadness array.</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> stockPrices <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">120.50</span><span class="token punctuation">,</span> <span class="token number">122.10</span><span class="token punctuation">,</span> <span class="token number">119.80</span><span class="token punctuation">,</span> <span class="token number">125.00</span><span class="token punctuation">,</span> <span class="token number">121.75</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Stock Prices:"</span><span class="token punctuation">,</span> stockPrices<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> lowestPrice <span class="token operator">=</span> stockPrices<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Lowest price:"</span><span class="token punctuation">,</span> lowestPrice<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 119.8</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> highestPrice <span class="token operator">=</span> stockPrices<span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Highest price:"</span><span class="token punctuation">,</span> highestPrice<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 125</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="sum" tabindex="-1"><a class="header-anchor" href="#sum"><span>sum()</span></a></h4>
<p>Calculate the total sum of all numbers in your array. We saw this earlier with axes, but here's a simple example.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> monthlyExpenses <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">300</span><span class="token punctuation">,</span> <span class="token number">150</span><span class="token punctuation">,</span> <span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Monthly Expenses:"</span><span class="token punctuation">,</span> monthlyExpenses<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> totalExpenses <span class="token operator">=</span> monthlyExpenses<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Total Monthly Expenses:"</span><span class="token punctuation">,</span> totalExpenses<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: 845</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="logic" tabindex="-1"><a class="header-anchor" href="#logic"><span>Logic</span></a></h3>
<p>To check for specific conditions in your data, Openmadness makes it easy to compare numbers within your arrays. These operations create a new Openmadness array where each value is true or false (also known as a boolean).</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> sensorReadings <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sensor Readings:"</span><span class="token punctuation">,</span> sensorReadings<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is each reading greater than 20?</span></span>
<span class="line"><span class="token keyword">const</span> aboveThreshold <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">greaterThan</span><span class="token punctuation">(</span><span class="token number">20</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings > 20:"</span><span class="token punctuation">,</span> aboveThreshold<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [false, true, false, true, false, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is each reading less than or equal to 15?</span></span>
<span class="line"><span class="token keyword">const</span> belowOrEqual <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">lessThanOrEqual</span><span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings &lt;= 15:"</span><span class="token punctuation">,</span> belowOrEqual<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [true, false, true, false, false, false]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is any reading exactly 30?</span></span>
<span class="line"><span class="token keyword">const</span> isThirty <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">equal</span><span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings == 30:"</span><span class="token punctuation">,</span> isThirty<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [false, false, false, false, false, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Is any reading NOT equal to 19?</span></span>
<span class="line"><span class="token keyword">const</span> notNineteen <span class="token operator">=</span> sensorReadings<span class="token punctuation">.</span><span class="token function">notEqual</span><span class="token punctuation">(</span><span class="token number">19</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Readings != 19:"</span><span class="token punctuation">,</span> notNineteen<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [true, true, true, true, false, true]</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="advanced" tabindex="-1"><a class="header-anchor" href="#advanced"><span>Advanced</span></a></h2>
</div></template>


